services:
  - type: web
    name: status-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "daphne -b 0.0.0.0 -p 8000 statuspage.asgi:application"
    envVars:
      - key: SECRET_KEY
        value: your-secret-key
